#!/usr/bin/env bash
# Vercel build step for the RAVEN Control Room frontend.
#
# Assembles a purely static site into ./public:
#   - copies raven/web/static/* (index.html, app.js, styles.css, config.js)
#   - copies the RAVEN.png logo to /raven.png (the frontend requests /raven.png)
#   - rewrites config.js with the Render backend URL from $RAVEN_API_BASE
#
# Set RAVEN_API_BASE in the Vercel project env, e.g.
#   RAVEN_API_BASE=https://raven-backend.onrender.com
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/raven/web/static"
OUT="$ROOT/public"

rm -rf "$OUT"
mkdir -p "$OUT"

cp "$SRC/index.html" "$OUT/index.html"
cp "$SRC/app.js"     "$OUT/app.js"
cp "$SRC/styles.css" "$OUT/styles.css"
cp "$SRC/control-room.css" "$OUT/control-room.css"

# The frontend references /raven.png; ship the logo under that path.
cp "$ROOT/RAVEN.png" "$OUT/raven.png"

# Inject the backend URL. Fall back to same-origin if unset (won't work on
# Vercel since there's no backend there, but keeps the build from failing).
API_BASE="${RAVEN_API_BASE:-}"
# Strip any trailing slash for a clean base.
API_BASE="${API_BASE%/}"

cat > "$OUT/config.js" <<EOF
/* Generated by scripts/build_frontend.sh at deploy time. Do not edit. */
window.RAVEN_API_BASE = "${API_BASE}";
EOF

echo "Built frontend -> $OUT"
echo "  RAVEN_API_BASE = ${API_BASE:-<empty>}"
ls -la "$OUT"
